planner_client:
  ros__parameters:
    plan_solver_timeout: 15.0  
planner:
  ros__parameters:
    plan_solver_timeout: 15.0  
    plan_solver_plugins: ["POPF"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    TFD:
      plugin: "plansys2/TFDPlanSolver"
    TAMER:
      plugin: "plansys2/TAMERPlanSolver"
solver:
  ros__parameters:
    solver_timeout: 240.0
    summarize_mode: "limited"
    prompt_debug: false
    solver_plugins: ["LLAMA"]
    LLAMA:
      plugin: "plansys2/LLAMASolver"
      llm_debug: true
      pre_launch: true  # false = re-launch LLM per solve (slower, frees RAM between solves)
      model_yaml: "~/TFG/src/llm/llama_ros/llama_bringup/models/Qwen2.5-3B.yaml"
executor:
  ros__parameters:
    bt_builder_plugin: "SimpleBTBuilder"
    # bt_builder_plugin: "STNBTBuilder"